use std::fs;
use std::path::Path;

// Include the shared parsing/codegen logic from the lib source.
// This avoids duplicating the code between build.rs and the main crate.
// The module's #[cfg(test)] tests run via `cargo test --lib`.
#[path = "src/schema/codegen.rs"]
mod codegen;

use codegen::{generate_migrations_module, parse_migration_filename};

/// Scan migration directories and generate Rust modules.
fn generate_migration_modules() {
    let migrations_dir = Path::new("migrations");
    if !migrations_dir.is_dir() {
        return;
    }

    // Tell Cargo to re-run if migrations or the codegen logic changes.
    // Once any rerun-if-changed is emitted, Cargo's default "any file" tracking
    // is disabled — so we must explicitly list codegen.rs too.
    println!("cargo::rerun-if-changed=migrations/");
    println!("cargo::rerun-if-changed=src/schema/codegen.rs");

    let schema_dir = Path::new("src/schema");
    fs::create_dir_all(schema_dir).expect("failed to create src/schema/");

    let mut entries: Vec<_> = fs::read_dir(migrations_dir)
        .expect("failed to read migrations/")
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let db_name = entry.file_name().to_string_lossy().to_string();

        // Collect and parse SQL files
        let mut sql_files: Vec<_> = fs::read_dir(entry.path())
            .expect("failed to read migration subdirectory")
            .filter_map(|e| e.ok())
            .filter(|e| e.file_name().to_string_lossy().ends_with(".sql"))
            .collect();
        sql_files.sort_by_key(|e| e.file_name());

        let mut migrations = Vec::new();
        for file in &sql_files {
            let filename = file.file_name().to_string_lossy().to_string();
            if let Some(parsed) = parse_migration_filename(&filename) {
                migrations.push(parsed);
            } else {
                println!("cargo::warning=Skipping migration file with invalid name: {db_name}/{filename}");
            }
        }

        // Sort by version (chronological)
        migrations.sort();

        let module_src = generate_migrations_module(&db_name, &migrations);
        let out_path = schema_dir.join(format!("{db_name}.rs"));
        fs::write(&out_path, module_src).unwrap_or_else(|e| {
            panic!("failed to write {}: {e}", out_path.display());
        });
    }
}

/// Scan workflows/ and generate a Rust module with include_str! for each YAML file.
fn generate_workflow_loader() {
    let workflows_dir = Path::new("workflows");
    if !workflows_dir.is_dir() {
        return;
    }

    println!("cargo::rerun-if-changed=workflows/");

    let mut yaml_files: Vec<String> = fs::read_dir(workflows_dir)
        .expect("failed to read workflows/")
        .filter_map(|e| e.ok())
        .filter_map(|e| {
            let name = e.file_name().to_string_lossy().to_string();
            if name.ends_with(".yaml") || name.ends_with(".yml") {
                Some(name)
            } else {
                None
            }
        })
        .collect();
    yaml_files.sort();

    let mut module_src = String::from(
        "// Auto-generated by build.rs — do not edit manually.\n\n\
         pub const BUNDLED_WORKFLOWS: &[&str] = &[\n",
    );
    for name in &yaml_files {
        module_src.push_str(&format!("    include_str!(\"../../workflows/{name}\"),\n"));
    }
    module_src.push_str("];\n");

    let workflow_dir = Path::new("src/workflow");
    fs::create_dir_all(workflow_dir).expect("failed to create src/workflow/");
    let out_path = workflow_dir.join("bundled.rs");
    // Only write if content changed to avoid triggering Tauri's file watcher loop
    let needs_write = match fs::read_to_string(&out_path) {
        Ok(existing) => existing != module_src,
        Err(_) => true,
    };
    if needs_write {
        fs::write(&out_path, module_src).unwrap_or_else(|e| {
            panic!("failed to write {}: {e}", out_path.display());
        });
    }
}

fn main() {
    generate_migration_modules();
    generate_workflow_loader();
    tauri_build::build()
}
