//! Migration filename parsing and code generation.
//!
//! Shared between `build.rs` (which generates migration modules at compile time)
//! and the lib (for testing). Included by build.rs via `#[path]`.

use std::fmt::Write as _;

/// A parsed migration file entry.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) struct ParsedMigration {
    /// Timestamp version string (e.g. "20260401000000").
    pub version: String,
    /// Human-readable name (e.g. "initial_schema").
    pub name: String,
    /// Original filename.
    pub filename: String,
    /// Whether this is an optional migration (.optional.sql).
    pub allow_failure: bool,
}

/// Parse a migration filename into its components.
///
/// Expected format: `YYYYMMDDHHMMSS_description.sql` or
/// `YYYYMMDDHHMMSS_description.optional.sql`.
///
/// Returns `None` if the filename doesn't match the expected pattern.
pub(crate) fn parse_migration_filename(filename: &str) -> Option<ParsedMigration> {
    // Check for .optional.sql vs .sql suffix
    let (stem, allow_failure) = if let Some(s) = filename.strip_suffix(".optional.sql") {
        (s, true)
    } else if let Some(s) = filename.strip_suffix(".sql") {
        (s, false)
    } else {
        return None;
    };

    // Split on first underscore: version_name
    let underscore_pos = stem.find('_')?;
    let version = &stem[..underscore_pos];
    let name = &stem[underscore_pos + 1..];

    // Version must be exactly 14 digits (YYYYMMDDHHMMSS)
    if version.len() != 14 || !version.chars().all(|c| c.is_ascii_digit()) {
        return None;
    }

    // Name must be non-empty
    if name.is_empty() {
        return None;
    }

    Some(ParsedMigration {
        version: version.to_string(),
        name: name.to_string(),
        filename: filename.to_string(),
        allow_failure,
    })
}

/// Generate a Rust module source string for a set of parsed migrations.
pub(crate) fn generate_migrations_module(db_name: &str, migrations: &[ParsedMigration]) -> String {
    let mut out = String::new();
    writeln!(out, "// AUTO-GENERATED by build.rs — do not edit").unwrap();
    writeln!(out, "use super::Migration;").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub(crate) const MIGRATIONS: &[Migration] = &[").unwrap();

    for m in migrations {
        let include_path = format!("../../migrations/{}/{}", db_name, m.filename);
        writeln!(out, "    Migration {{").unwrap();
        writeln!(out, "        version: \"{}\",", m.version).unwrap();
        writeln!(out, "        name: \"{}\",", m.name).unwrap();
        // Use multi-line include_str! when the path would exceed rustfmt's line width
        if include_path.len() + "        sql: include_str!(\"\"),".len() > 100 {
            writeln!(out, "        sql: include_str!(").unwrap();
            writeln!(out, "            \"{include_path}\"").unwrap();
            writeln!(out, "        ),").unwrap();
        } else {
            writeln!(out, "        sql: include_str!(\"{include_path}\"),").unwrap();
        }
        writeln!(out, "        allow_failure: {},", m.allow_failure).unwrap();
        writeln!(out, "    }},").unwrap();
    }

    writeln!(out, "];").unwrap();
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_migration_filename() {
        let result = parse_migration_filename("20260401000000_initial_schema.sql").unwrap();
        assert_eq!(result.version, "20260401000000");
        assert_eq!(result.name, "initial_schema");
        assert!(!result.allow_failure);
        assert_eq!(result.filename, "20260401000000_initial_schema.sql");
    }

    #[test]
    fn test_parse_optional_migration_filename() {
        let result = parse_migration_filename("20260401000001_vector_index.optional.sql").unwrap();
        assert_eq!(result.version, "20260401000001");
        assert_eq!(result.name, "vector_index");
        assert!(result.allow_failure);
    }

    #[test]
    fn test_parse_rejects_invalid_filename() {
        // No timestamp prefix
        assert!(parse_migration_filename("bad_name.sql").is_none());
        // Wrong extension
        assert!(parse_migration_filename("20260401000000_test.txt").is_none());
        // Too short timestamp
        assert!(parse_migration_filename("2026_test.sql").is_none());
        // Missing underscore separator
        assert!(parse_migration_filename("20260401000000.sql").is_none());
        // Empty name
        assert!(parse_migration_filename("20260401000000_.sql").is_none());
    }

    #[test]
    fn test_filenames_sort_chronologically() {
        let mut migrations = vec![
            parse_migration_filename("20260402000000_second.sql").unwrap(),
            parse_migration_filename("20260401000000_first.sql").unwrap(),
            parse_migration_filename("20260403000000_third.sql").unwrap(),
        ];
        migrations.sort();

        assert_eq!(migrations[0].version, "20260401000000");
        assert_eq!(migrations[1].version, "20260402000000");
        assert_eq!(migrations[2].version, "20260403000000");
    }

    #[test]
    fn test_generate_migrations_module() {
        let migrations = vec![
            ParsedMigration {
                version: "20260401000000".to_string(),
                name: "initial_schema".to_string(),
                filename: "20260401000000_initial_schema.sql".to_string(),
                allow_failure: false,
            },
            ParsedMigration {
                version: "20260401000001".to_string(),
                name: "vector_index".to_string(),
                filename: "20260401000001_vector_index.optional.sql".to_string(),
                allow_failure: true,
            },
        ];

        let output = generate_migrations_module("conversations", &migrations);

        assert!(output.contains("// AUTO-GENERATED by build.rs"));
        assert!(output.contains("use super::Migration;"));
        assert!(output.contains("pub(crate) const MIGRATIONS: &[Migration]"));
        assert!(output.contains("version: \"20260401000000\""));
        assert!(output.contains("name: \"initial_schema\""));
        assert!(output.contains(
            "include_str!(\"../../migrations/conversations/20260401000000_initial_schema.sql\")"
        ));
        assert!(output.contains("allow_failure: false"));
        assert!(output.contains("version: \"20260401000001\""));
        assert!(output.contains("allow_failure: true"));
    }
}
