// AUTO-GENERATED by build.rs — do not edit
use super::Migration;

pub(crate) const MIGRATIONS: &[Migration] = &[
    Migration {
        version: "20260401000000",
        name: "initial_schema",
        sql: include_str!("../../migrations/conversations/20260401000000_initial_schema.sql"),
        allow_failure: false,
    },
    Migration {
        version: "20260401000001",
        name: "vector_index",
        sql: include_str!(
            "../../migrations/conversations/20260401000001_vector_index.optional.sql"
        ),
        allow_failure: true,
    },
];
