// This file will be auto-generated by tauri-specta when running `bun run tauri:dev`.
// It is a typed stub that matches the tauri-specta rc.21 output format.
// All commands use invoke() internally; all events use listen() internally.
// Replace this file with the generated output once `tauri:dev` can run.

import { invoke } from "@tauri-apps/api/core";
import { listen, type UnlistenFn } from "@tauri-apps/api/event";

// ── Re-exported types (mirror Rust serde structs) ──

export type {
  Ticket,
  TicketComment,
  TicketSection,
  TicketStatus,
  TicketType,
  SectionType,
  AcceptanceCriterion,
  ChecklistItem,
  KeyValueEntry,
  MarkdownContent,
  AcceptanceCriteriaContent,
  ChecklistContent,
  KeyValueContent,
} from "@/shared/lib/tickets/types";

export type {
  WorkflowDefinition,
  WorkflowStep,
  WorkflowState,
  WorkflowSuggestion,
  StepExecutionResult,
  StepStatus,
  StepRecord,
  DiffFile,
  DiffHunk,
  DiffLine,
  BranchInfo,
  CommitActionResult,
  StreamChunk,
  PermissionRequest,
  FeedbackRequestEvent,
  SectionUpdateEvent,
  SubtaskCreatedEvent,
  SubtaskUpdatedEvent,
  SubtaskClosedEvent,
  NotificationEvent,
  StepCompleteEvent,
  StatusUpdateEvent,
  ReviewFinding,
  ReviewComment,
  ReviewSubmission,
} from "@/shared/types";

// ── Locally-defined types (match Rust structs not yet in shared/types) ──

export interface ClaudeStatus {
  installed: boolean;
  authenticated: boolean;
  path: string | null;
  message: string;
}

export interface AppPreferences {
  theme: string;
}

export interface ProjectSettings {
  sync?: {
    enabled: boolean;
    provider: string;
    auto_push: boolean;
    config: Record<string, string>;
  };
  worktree?: {
    setup_command?: string;
  };
}

export interface TicketSectionDef {
  id: string;
  label: string;
  type: string;
  collapsed: boolean;
}

// Internal event payload types for Rust-derived events
export interface AgentPermissionRequestPayload {
  request_id: string;
  tool_name: string;
  input: Record<string, unknown>;
}

export interface AgentFeedbackRequestPayload {
  request_id: string;
  ticket_id: string;
  summary: string;
}

export interface AgentReviewFindingsRequestPayload {
  request_id: string;
  ticket_id: string;
  findings: unknown;
  summary: string;
}

export interface PrUrlReportedEventPayload {
  ticket_id: string;
  url: string;
}

// ── Helper to create typed event wrappers ──

function createEvent<T>(name: string) {
  return {
    listen: (handler: (event: { payload: T }) => void): Promise<UnlistenFn> =>
      listen<T>(name, handler),
  };
}

// ── Commands ──
// Parameter names use camelCase (Rust snake_case → TypeScript camelCase).
// AppHandle and State<'_, T> params are excluded (managed by Tauri internally).

export const commands = {
  // ── Folder dialog ──
  openFolderDialog: (): Promise<string | null> =>
    invoke<string | null>("open_folder_dialog"),

  // ── Claude ──
  claudeStatus: (): Promise<ClaudeStatus> =>
    invoke<ClaudeStatus>("claude_status"),

  claudeLogin: (): Promise<ClaudeStatus> =>
    invoke<ClaudeStatus>("claude_login"),

  // ── Agent ──
  agentPermissionRespond: (args: {
    requestId: string;
    allowed: boolean;
  }): Promise<void> => invoke<void>("agent_permission_respond", args),

  agentFeedbackRespond: (args: {
    requestId: string;
    approved: boolean;
    feedback?: string | null;
  }): Promise<void> => invoke<void>("agent_feedback_respond", args),

  agentReviewRespond: (args: {
    requestId: string;
    submission: unknown;
  }): Promise<void> => invoke<void>("agent_review_respond", args),

  // ── Tickets ──
  ticketList: (args: {
    projectDir: string;
    status?: string | null;
    ticketType?: string | null;
    showAll?: boolean | null;
  }): Promise<import("@/shared/lib/tickets/types").Ticket[]> =>
    invoke("ticket_list", args),

  ticketCreate: (args: {
    projectDir: string;
    title: string;
    description?: string | null;
    ticketType?: string | null;
    priority?: number | null;
  }): Promise<import("@/shared/lib/tickets/types").Ticket> =>
    invoke("ticket_create", args),

  ticketUpdate: (args: {
    projectDir: string;
    id: string;
    title?: string | null;
    status?: string | null;
    priority?: number | null;
    description?: string | null;
    notes?: string | null;
    design?: string | null;
    acceptanceCriteria?: string | null;
    metadata?: string | null;
  }): Promise<import("@/shared/lib/tickets/types").Ticket> =>
    invoke("ticket_update", args),

  ticketClose: (args: {
    projectDir: string;
    id: string;
    reason?: string | null;
  }): Promise<import("@/shared/lib/tickets/types").Ticket> =>
    invoke("ticket_close", args),

  ticketShow: (args: {
    projectDir: string;
    id: string;
  }): Promise<import("@/shared/lib/tickets/types").Ticket> =>
    invoke("ticket_show", args),

  ticketDelete: (args: { projectDir: string; id: string }): Promise<void> =>
    invoke("ticket_delete", args),

  ticketAddComment: (args: {
    projectDir: string;
    id: string;
    text: string;
  }): Promise<import("@/shared/lib/tickets/types").Ticket> =>
    invoke("ticket_add_comment", args),

  ticketUpdateSection: (args: {
    projectDir: string;
    ticketId: string;
    sectionId: string;
    content: unknown;
  }): Promise<import("@/shared/lib/tickets/types").Ticket> =>
    invoke("ticket_update_section", args),

  ticketInitializeSections: (args: {
    projectDir: string;
    ticketId: string;
    sectionDefs: TicketSectionDef[];
  }): Promise<import("@/shared/lib/tickets/types").Ticket> =>
    invoke("ticket_initialize_sections", args),

  // ── Settings ──
  settingsGet: (args: { projectDir: string }): Promise<ProjectSettings> =>
    invoke("settings_get", args),

  settingsUpdate: (args: {
    projectDir: string;
    settings: ProjectSettings;
  }): Promise<void> => invoke("settings_update", args),

  // ── Sync ──
  syncPullAll: (args: {
    projectDir: string;
  }): Promise<import("@/shared/lib/tickets/types").Ticket[]> =>
    invoke("sync_pull_all", args),

  syncPushTicket: (args: {
    projectDir: string;
    id: string;
  }): Promise<string> => invoke("sync_push_ticket", args),

  // ── Workflow ──
  workflowList: (args: {
    projectDir: string;
  }): Promise<import("@/shared/types").WorkflowDefinition[]> =>
    invoke("workflow_list", args),

  workflowGet: (args: {
    projectDir: string;
    workflowId: string;
  }): Promise<import("@/shared/types").WorkflowDefinition> =>
    invoke("workflow_get", args),

  workflowAssign: (args: {
    projectDir: string;
    issueId: string;
    workflowId: string;
  }): Promise<import("@/shared/types").WorkflowState> =>
    invoke("workflow_assign", args),

  workflowAdvance: (args: {
    projectDir: string;
    issueId: string;
  }): Promise<import("@/shared/types").WorkflowState> =>
    invoke("workflow_advance", args),

  workflowState: (args: {
    projectDir: string;
    issueId: string;
  }): Promise<import("@/shared/types").WorkflowState | null> =>
    invoke("workflow_state", args),

  workflowExecuteStep: (args: {
    projectDir: string;
    issueId: string;
  }): Promise<import("@/shared/types").StepExecutionResult> =>
    invoke("workflow_execute_step", args),

  workflowSuggest: (args: {
    projectDir: string;
    issueId: string;
  }): Promise<import("@/shared/types").WorkflowSuggestion> =>
    invoke("workflow_suggest", args),

  workflowGetDiff: (args: {
    projectDir: string;
    baseCommit?: string | null;
  }): Promise<import("@/shared/types").DiffFile[]> =>
    invoke("workflow_get_diff", args),

  workflowGetBranchInfo: (args: {
    projectDir: string;
  }): Promise<import("@/shared/types").BranchInfo> =>
    invoke("workflow_get_branch_info", args),

  workflowExecuteCommitAction: (args: {
    projectDir: string;
    issueId: string;
    action: string;
    commitMessage: string;
  }): Promise<import("@/shared/types").CommitActionResult> =>
    invoke("workflow_execute_commit_action", args),

  workflowCleanupWorktree: (args: {
    projectDir: string;
    issueId: string;
  }): Promise<void> => invoke("workflow_cleanup_worktree", args),

  // ── Preferences ──
  getAppPreferences: (): Promise<AppPreferences> =>
    invoke("get_app_preferences"),

  setAppPreferences: (args: {
    preferences: AppPreferences;
  }): Promise<void> => invoke("set_app_preferences", args),

  openPreferencesWindow: (): Promise<void> =>
    invoke("open_preferences_window"),
};

// ── Events ──
// Event names match the Rust struct names (tauri-specta default: PascalCase).

export const events = {
  // StreamChunk — emitted for each streaming chunk from the agent
  streamChunk: createEvent<import("@/shared/types").StreamChunk>("StreamChunk"),

  // AgentPermissionRequest — agent requests permission for a dangerous tool
  agentPermissionRequest: createEvent<AgentPermissionRequestPayload>(
    "AgentPermissionRequest"
  ),

  // AgentFeedbackRequest — agent requests user feedback before continuing
  agentFeedbackRequest: createEvent<AgentFeedbackRequestPayload>(
    "AgentFeedbackRequest"
  ),

  // AgentReviewFindingsRequest — agent requests review of its findings
  agentReviewFindingsRequest: createEvent<AgentReviewFindingsRequestPayload>(
    "AgentReviewFindingsRequest"
  ),

  // SubtaskCreated — agent created a child ticket
  subtaskCreated: createEvent<import("@/shared/types").SubtaskCreatedEvent>(
    "SubtaskCreated"
  ),

  // SubtaskUpdated — agent updated a child ticket
  subtaskUpdated: createEvent<import("@/shared/types").SubtaskUpdatedEvent>(
    "SubtaskUpdated"
  ),

  // SubtaskClosed — agent closed a child ticket
  subtaskClosed: createEvent<import("@/shared/types").SubtaskClosedEvent>(
    "SubtaskClosed"
  ),

  // SectionUpdateEvent — agent updated a ticket section
  sectionUpdateEvent: createEvent<import("@/shared/types").SectionUpdateEvent>(
    "SectionUpdateEvent"
  ),

  // NotificationEvent — agent sent a notification
  notificationEvent: createEvent<import("@/shared/types").NotificationEvent>(
    "NotificationEvent"
  ),

  // StepCompleteEvent — agent completed a workflow step
  stepCompleteEvent: createEvent<import("@/shared/types").StepCompleteEvent>(
    "StepCompleteEvent"
  ),

  // StatusUpdateEvent — agent provided a status update
  statusUpdateEvent: createEvent<import("@/shared/types").StatusUpdateEvent>(
    "StatusUpdateEvent"
  ),

  // PrUrlReportedEvent — agent reported a pull request URL
  prUrlReportedEvent: createEvent<PrUrlReportedEventPayload>(
    "PrUrlReportedEvent"
  ),

  // AppPreferences — cross-window sync when preferences change
  appPreferences: createEvent<AppPreferences>("AppPreferences"),
};
