
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async openFolderDialog() : Promise<string | null> {
    return await TAURI_INVOKE("open_folder_dialog");
},
async claudeStatus() : Promise<ClaudeStatus> {
    return await TAURI_INVOKE("claude_status");
},
async claudeLogin() : Promise<ClaudeStatus> {
    return await TAURI_INVOKE("claude_login");
},
async agentPermissionRespond(issueId: string, requestId: string, allowed: boolean) : Promise<null> {
    return await TAURI_INVOKE("agent_permission_respond", { issueId, requestId, allowed });
},
async agentReviewRespond(issueId: string, requestId: string, submission: JsonValue) : Promise<null> {
    return await TAURI_INVOKE("agent_review_respond", { issueId, requestId, submission });
},
async agentSetModel(issueId: string, model: string) : Promise<null> {
    return await TAURI_INVOKE("agent_set_model", { issueId, model });
},
async agentSetThinking(issueId: string, thinkingType: string, budgetTokens: number | null) : Promise<null> {
    return await TAURI_INVOKE("agent_set_thinking", { issueId, thinkingType, budgetTokens });
},
async agentSetEffort(issueId: string, effort: string) : Promise<null> {
    return await TAURI_INVOKE("agent_set_effort", { issueId, effort });
},
async agentSetFastMode(issueId: string, enabled: boolean) : Promise<null> {
    return await TAURI_INVOKE("agent_set_fast_mode", { issueId, enabled });
},
async setAutoAdvance(projectDir: string, issueId: string, enabled: boolean) : Promise<null> {
    return await TAURI_INVOKE("set_auto_advance", { projectDir, issueId, enabled });
},
async getAutoAdvance(projectDir: string, issueId: string) : Promise<boolean> {
    return await TAURI_INVOKE("get_auto_advance", { projectDir, issueId });
},
async ticketList(projectDir: string, status: string | null, ticketType: string | null, showAll: boolean | null) : Promise<Ticket[]> {
    return await TAURI_INVOKE("ticket_list", { projectDir, status, ticketType, showAll });
},
async ticketCreate(projectDir: string, title: string, description: string | null, ticketType: string | null, priority: number | null) : Promise<Ticket> {
    return await TAURI_INVOKE("ticket_create", { projectDir, title, description, ticketType, priority });
},
async ticketUpdate(projectDir: string, id: string, title: string | null, status: string | null, priority: number | null, description: string | null, notes: string | null, design: string | null, acceptanceCriteria: string | null, metadata: string | null) : Promise<Ticket> {
    return await TAURI_INVOKE("ticket_update", { projectDir, id, title, status, priority, description, notes, design, acceptanceCriteria, metadata });
},
async ticketClose(projectDir: string, id: string, reason: string | null) : Promise<Ticket> {
    return await TAURI_INVOKE("ticket_close", { projectDir, id, reason });
},
async ticketShow(projectDir: string, id: string) : Promise<Ticket> {
    return await TAURI_INVOKE("ticket_show", { projectDir, id });
},
async ticketDelete(projectDir: string, id: string) : Promise<null> {
    return await TAURI_INVOKE("ticket_delete", { projectDir, id });
},
async ticketAddComment(projectDir: string, id: string, text: string) : Promise<Ticket> {
    return await TAURI_INVOKE("ticket_add_comment", { projectDir, id, text });
},
async ticketUpdateSection(projectDir: string, ticketId: string, sectionId: string, content: JsonValue) : Promise<Ticket> {
    return await TAURI_INVOKE("ticket_update_section", { projectDir, ticketId, sectionId, content });
},
async ticketInitializeSections(projectDir: string, ticketId: string, sectionDefs: TicketSectionDef[]) : Promise<Ticket> {
    return await TAURI_INVOKE("ticket_initialize_sections", { projectDir, ticketId, sectionDefs });
},
async settingsGet(projectDir: string) : Promise<ProjectSettings> {
    return await TAURI_INVOKE("settings_get", { projectDir });
},
async settingsUpdate(projectDir: string, settings: ProjectSettings) : Promise<null> {
    return await TAURI_INVOKE("settings_update", { projectDir, settings });
},
async conversationSetEncryption(projectDir: string, key: string | null) : Promise<null> {
    return await TAURI_INVOKE("conversation_set_encryption", { projectDir, key });
},
async conversationEncryptionStatus(projectDir: string) : Promise<boolean> {
    return await TAURI_INVOKE("conversation_encryption_status", { projectDir });
},
async conversationRestore(projectDir: string, ticketId: string) : Promise<ConversationSnapshot | null> {
    return await TAURI_INVOKE("conversation_restore", { projectDir, ticketId });
},
async conversationList(projectDir: string) : Promise<ConversationSummary[]> {
    return await TAURI_INVOKE("conversation_list", { projectDir });
},
async conversationSearch(projectDir: string, query: string, ticketId: string | null, limit: number | null) : Promise<SearchResult[]> {
    return await TAURI_INVOKE("conversation_search", { projectDir, query, ticketId, limit });
},
async conversationStats(projectDir: string, ticketId: string) : Promise<ConversationStats> {
    return await TAURI_INVOKE("conversation_stats", { projectDir, ticketId });
},
async conversationLoadTurn(projectDir: string, ticketId: string, turnId: string) : Promise<ConversationEventRecord[]> {
    return await TAURI_INVOKE("conversation_load_turn", { projectDir, ticketId, turnId });
},
async conversationListTurns(projectDir: string, ticketId: string) : Promise<TurnSummary[]> {
    return await TAURI_INVOKE("conversation_list_turns", { projectDir, ticketId });
},
async conversationCheckpoints(projectDir: string, ticketId: string) : Promise<CheckpointRecord[]> {
    return await TAURI_INVOKE("conversation_checkpoints", { projectDir, ticketId });
},
async conversationCheckpointForTurn(projectDir: string, ticketId: string, turnId: string) : Promise<CheckpointRecord | null> {
    return await TAURI_INVOKE("conversation_checkpoint_for_turn", { projectDir, ticketId, turnId });
},
async conversationCleanup(projectDir: string, maxAgeDays: number | null, maxConversations: number | null) : Promise<CleanupResult> {
    return await TAURI_INVOKE("conversation_cleanup", { projectDir, maxAgeDays, maxConversations });
},
async conversationSemanticSearch(projectDir: string, query: string, ticketId: string | null, limit: number | null) : Promise<SemanticSearchResult[]> {
    return await TAURI_INVOKE("conversation_semantic_search", { projectDir, query, ticketId, limit });
},
async conversationHybridSearch(projectDir: string, query: string, ticketId: string | null, limit: number | null) : Promise<HybridSearchResult[]> {
    return await TAURI_INVOKE("conversation_hybrid_search", { projectDir, query, ticketId, limit });
},
async conversationRagContext(projectDir: string, taskDescription: string, maxTokens: number | null) : Promise<ContextChunk[]> {
    return await TAURI_INVOKE("conversation_rag_context", { projectDir, taskDescription, maxTokens });
},
async conversationRelated(projectDir: string, ticketId: string, limit: number | null) : Promise<RelatedConversation[]> {
    return await TAURI_INVOKE("conversation_related", { projectDir, ticketId, limit });
},
async listProjectFiles(projectDir: string) : Promise<string[]> {
    return await TAURI_INVOKE("list_project_files", { projectDir });
},
async workflowList(projectDir: string) : Promise<WorkflowDefinition[]> {
    return await TAURI_INVOKE("workflow_list", { projectDir });
},
async workflowGet(projectDir: string, workflowId: string) : Promise<WorkflowDefinition> {
    return await TAURI_INVOKE("workflow_get", { projectDir, workflowId });
},
async workflowAssign(projectDir: string, issueId: string, workflowId: string) : Promise<WorkflowState> {
    return await TAURI_INVOKE("workflow_assign", { projectDir, issueId, workflowId });
},
async workflowAdvance(projectDir: string, issueId: string) : Promise<WorkflowState> {
    return await TAURI_INVOKE("workflow_advance", { projectDir, issueId });
},
async workflowState(projectDir: string, issueId: string) : Promise<WorkflowState | null> {
    return await TAURI_INVOKE("workflow_state", { projectDir, issueId });
},
async workflowExecuteStep(projectDir: string, issueId: string, onChunk: TAURI_CHANNEL<StreamChunk>, userMessage: string | null) : Promise<StepExecutionResult> {
    return await TAURI_INVOKE("workflow_execute_step", { projectDir, issueId, onChunk, userMessage });
},
async workflowSuggest(projectDir: string, issueId: string, onChunk: TAURI_CHANNEL<StreamChunk>) : Promise<WorkflowSuggestion> {
    return await TAURI_INVOKE("workflow_suggest", { projectDir, issueId, onChunk });
},
async workflowGetDiff(projectDir: string, baseCommit: string | null) : Promise<DiffFile[]> {
    return await TAURI_INVOKE("workflow_get_diff", { projectDir, baseCommit });
},
async workflowGetBranchInfo(projectDir: string) : Promise<BranchInfo> {
    return await TAURI_INVOKE("workflow_get_branch_info", { projectDir });
},
async workflowExecuteCommitAction(projectDir: string, issueId: string, action: string, commitMessage: string, onChunk: TAURI_CHANNEL<StreamChunk>) : Promise<CommitActionResult> {
    return await TAURI_INVOKE("workflow_execute_commit_action", { projectDir, issueId, action, commitMessage, onChunk });
},
async workflowCleanupWorktree(projectDir: string, issueId: string) : Promise<null> {
    return await TAURI_INVOKE("workflow_cleanup_worktree", { projectDir, issueId });
},
async getAppPreferences() : Promise<AppPreferences> {
    return await TAURI_INVOKE("get_app_preferences");
},
async setAppPreferences(preferences: AppPreferences) : Promise<null> {
    return await TAURI_INVOKE("set_app_preferences", { preferences });
},
async openPreferencesWindow() : Promise<null> {
    return await TAURI_INVOKE("open_preferences_window");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
agentInitMetadata: AgentInitMetadata,
agentPermissionRequest: AgentPermissionRequest,
agentReviewFindingsRequest: AgentReviewFindingsRequest,
agentSessionEnded: AgentSessionEnded,
appPreferences: AppPreferences,
notificationEvent: NotificationEvent,
prUrlReportedEvent: PrUrlReportedEvent,
sectionUpdateEvent: SectionUpdateEvent,
statusUpdateEvent: StatusUpdateEvent,
subtaskClosed: SubtaskClosed,
subtaskCreated: SubtaskCreated,
subtaskUpdated: SubtaskUpdated,
supervisorEvaluating: SupervisorEvaluating,
supervisorReply: SupervisorReply
}>({
agentInitMetadata: "agent-init-metadata",
agentPermissionRequest: "agent-permission-request",
agentReviewFindingsRequest: "agent-review-findings-request",
agentSessionEnded: "agent-session-ended",
appPreferences: "app-preferences",
notificationEvent: "notification-event",
prUrlReportedEvent: "pr-url-reported-event",
sectionUpdateEvent: "section-update-event",
statusUpdateEvent: "status-update-event",
subtaskClosed: "subtask-closed",
subtaskCreated: "subtask-created",
subtaskUpdated: "subtask-updated",
supervisorEvaluating: "supervisor-evaluating",
supervisorReply: "supervisor-reply"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Emitted when the agent sidecar initializes and reports its configuration.
 */
export type AgentInitMetadata = { issue_id: string; model: string; available_models: string[]; tools: string[]; slash_commands: string[]; skills: string[]; mcp_servers: McpServerInfo[] }
/**
 * Permission request received from the sidecar.
 */
export type AgentPermissionRequest = { issue_id: string; request_id: string; tool_name: string; input: JsonValue }
/**
 * Review findings request received from the sidecar.
 */
export type AgentReviewFindingsRequest = { request_id: string; ticket_id: string; findings: JsonValue; summary: string }
/**
 * Emitted when an agent session ends (timeout, error, or success).
 */
export type AgentSessionEnded = { issue_id: string }
export type AppPreferences = { theme?: string; context_indicator_visibility?: string }
/**
 * Branch information for the commit view.
 */
export type BranchInfo = { branch: string; remote_tracking?: string | null }
/**
 * A recorded git checkpoint associated with a conversation turn.
 */
export type CheckpointRecord = { ticket_id: string; turn_id: string; step_id: string; commit_hash: string; branch: string; timestamp: string }
/**
 * Status of the Claude Code CLI installation and authentication.
 */
export type ClaudeStatus = { installed: boolean; authenticated: boolean; path?: string | null; message: string }
/**
 * Result of a cleanup operation.
 */
export type CleanupResult = { deleted_count: number; freed_events: number }
/**
 * Result of a commit action executed via the agent sidecar.
 */
export type CommitActionResult = { success: boolean; message: string; commit_hash?: string | null; pr_url?: string | null }
/**
 * A chunk of context retrieved via RAG.
 */
export type ContextChunk = { ticket_id: string; step_id: string; step_label: string | null; content: string; timestamp: string; relevance: number }
export type ConversationEventRecord = { timestamp: string; sequence: number; step_id: string; event_type: string; content: string }
export type ConversationSnapshot = { schema_version: number; ticket_id: string; session_id: string | null; created_at: string; updated_at: string; status: string; events: ConversationEventRecord[]; steps: ConversationStepRecord[]; event_count: number }
/**
 * Aggregated conversation statistics exposed to the frontend via IPC.
 */
export type ConversationStats = { total_input_tokens: number; total_output_tokens: number; total_cache_reads: number; total_cache_writes: number; total_cost_usd: number; turn_count: number; model: string | null }
export type ConversationStepRecord = { step_id: string; label: string | null; started_at: string; completed_at: string | null; status: string; first_sequence: number }
export type ConversationSummary = { ticket_id: string; status: string; event_count: number; updated_at: string }
export type DiffFile = { path: string; status: string; additions: number; deletions: number; hunks: DiffHunk[] }
export type DiffHunk = { header: string; old_start: number; old_count: number; new_start: number; new_count: number; lines: DiffLine[] }
export type DiffLine = { line_type: DiffLineType; content: string; old_line_no?: number | null; new_line_no?: number | null }
export type DiffLineType = "added" | "removed" | "context"
/**
 * A result from hybrid (FTS5 + vector) search.
 */
export type HybridSearchResult = { ticket_id: string; step_id: string; content: string; timestamp: string; fts_rank: number | null; vector_distance: number | null; combined_score: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type McpServerInfo = { name: string; status: string }
/**
 * Emitted when the agent sends a notification.
 */
export type NotificationEvent = { title: string; message: string; level: string }
/**
 * Emitted when the agent reports a pull request URL.
 */
export type PrUrlReportedEvent = { ticket_id: string; url: string }
export type ProjectSettings = { worktree?: WorktreeSettings | null; supervisor?: SupervisorSettings | null; 
/**
 * Optional encryption key for the conversation database.
 * Future: move to OS keychain for better security.
 */
encryption_key?: string | null }
/**
 * A related conversation found via embedding similarity.
 */
export type RelatedConversation = { ticket_id: string; similarity: number; event_count: number; updated_at: string }
export type SearchResult = { ticket_id: string; step_id: string; event_type: string; content: string; timestamp: string; rank: number }
/**
 * Emitted when a ticket section is updated by the agent.
 */
export type SectionUpdateEvent = { ticket_id: string; section: string; section_id?: string | null; content: string }
/**
 * A result from semantic (vector) search.
 */
export type SemanticSearchResult = { ticket_id: string; step_id: string; content: string; timestamp: string; distance: number }
/**
 * Emitted when the agent provides a status update.
 */
export type StatusUpdateEvent = { ticket_id: string; status_text: string }
export type StepExecutionResult = { step_id: string; response: string; workflow_completed: boolean }
export type StepInstructions = { prompt: string } | { file: string }
export type StepRecord = { step_id: string; status: StepStatus; started_at: string | null; completed_at: string | null; output_summary: string | null }
export type StepStatus = "pending" | "in_progress" | "completed" | { failed: string }
export type StepViewType = "chat" | "review" | "progress" | "diff_review" | "commit"
/**
 * Streaming event payload emitted to frontend
 */
export type StreamChunk = { issue_id: string; chunk_type: string; content: string }
/**
 * Emitted when a subtask is closed by the agent.
 */
export type SubtaskClosed = { subtask_id: string; parent_id: string }
/**
 * Emitted when a subtask is created by the agent.
 */
export type SubtaskCreated = { subtask_id: string; parent_id: string }
/**
 * Emitted when a subtask is updated by the agent.
 */
export type SubtaskUpdated = { subtask_id: string; parent_id: string }
/**
 * Emitted when the supervisor starts evaluating.
 */
export type SupervisorEvaluating = { issue_id: string }
/**
 * Emitted when the supervisor auto-replies on behalf of the user.
 */
export type SupervisorReply = { issue_id: string; message: string; reasoning: string | null; turn_number: number }
export type SupervisorSettings = { 
/**
 * Custom supervisor system prompt (replaces guidelines section only).
 * None = use default prompt.
 */
custom_prompt?: string | null; 
/**
 * Max supervisor replies per step before falling back to user. Default: 5.
 */
max_replies_per_step?: number }
export type Ticket = { id: string; title: string; status: string; priority: number; ticket_type: string; description?: string | null; notes?: string | null; design?: string | null; acceptance_criteria?: string | null; assignee?: string | null; created_by?: string | null; created_at: string; updated_at: string; closed_at?: string | null; close_reason?: string | null; labels?: string[]; parent_id?: string | null; children_ids?: string[]; sections?: TicketSection[]; metadata?: JsonValue; comments?: TicketComment[] }
export type TicketComment = { id: string; author: string; text: string; created_at: string }
export type TicketSection = { id: string; label: string; type: string; content: JsonValue; collapsed?: boolean; source?: string; created_at?: string; updated_at?: string }
/**
 * Definition for initializing a ticket section from a workflow.
 */
export type TicketSectionDef = { id: string; label: string; type: string; collapsed?: boolean }
export type TurnSummary = { turn_id: string; start_sequence: number; end_sequence: number; event_count: number; first_event_type: string; timestamp: string }
export type WorkflowDefinition = { id: string; name: string; description: string; version: string; steps: WorkflowStep[]; ticket_sections?: WorkflowSectionDef[] }
export type WorkflowPhase = "research" | "plan" | "implementation" | "review"
export type WorkflowSectionDef = { id: string; label: string; type: string; collapsed?: boolean }
export type WorkflowState = { workflow_id: string; current_step_id: string | null; step_status: StepStatus; step_history: StepRecord[] }
export type WorkflowStep = { id: string; name: string; description: string; instructions: StepInstructions; view: StepViewType; phase: WorkflowPhase | null }
export type WorkflowSuggestion = { workflow_id: string; reasoning: string }
export type WorktreeSettings = { 
/**
 * Optional shell command to run after worktree creation (e.g., "bun install")
 */
setup_command?: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
