export const TOOL_LABELS: Record<string, string> = {
  Write: "Writing file",
  Read: "Reading file",
  Edit: "Editing file",
  MultiEdit: "Editing files",
  Bash: "Running command",
  Glob: "Searching files",
  Grep: "Searching content",
  Agent: "Running agent",
  WebSearch: "Searching web",
  WebFetch: "Fetching URL",
  FileRead: "Reading file",
  FileWrite: "Writing file",
  FileEdit: "Editing file",
  BashOutput: "Running command",
  Skill: "Running skill",
  TodoWrite: "Updating tasks",
  TodoRead: "Reading tasks",
  NotebookEdit: "Editing notebook",
  ListChecks: "Checking tasks",
};
